### ISSUE TITLE
Yocto activity bar does not list the recipes

### ISSUE THREAD

**Issue by microhobby** [yoctoproject/vscode-bitbake#10]
Even if the scan results in recipes found, they are not listed:

![image](https://github.com/yoctoproject/vscode-bitbake/assets/2633321/af9a822f-ca78-4aea-ae5d-e7fce6bb8263)

**Comment by microhobby** [comment]
I was expecting to have all listed, so I think that more users will have the same missed experience. A kind of filter text box to list only the match sounds good.

**Comment by deribaucourt** [comment]
Yes, a search filter and maybe a favorites star icon to pin frequently used recipes would do!

**Comment by Ehsan2754** [comment]
+ UX reflection: feels good as it is, missing a search. also there is no special feature practically than bitbake -c <command>. the intelisense and the definition navigation is a big deal . thanks for that.

**Comment by deribaucourt** [comment]
@Ehsan2754 We'll rely on the upcoming `devtool ide-sdk` command which will setup the C/Cpp extension just like you suggest: linting, cross-compiling with the SDK, SSH installation on the target and SSH cross debugging :) .
I just started integrating [devtool (very WIP)](https://github.com/yoctoproject/vscode-bitbake/pull/29) to this extension while Adrian Freihofer is iterating on devtool. Development for devtool happens on the mailing list: https://lists.openembedded.org/g/openembedded-core/search?p=recentpostdate%2Fsticky%2C%2C%2C20%2C2%2C0%2C0&q=ide-sdk

You can already try out `devtool ide-sdk` at https://git.yoctoproject.org/poky-contrib/log/?h=adrianf/devtool-ide

The idea is to present and manage devtool workspaces just like we do with the recipes panel you seem to enjoy :). There'll be a button to open the sources workspace in a separate VSCode window with everything already set up ! We'll only support CMake and Meson recipes initially, maybe with a fallback to `devtool build/deploy-target`.

Make sure to add a positive review on the VSCode marketplace if you enjoy our extension ;)

**Comment by Ehsan2754** [comment]
Great work. when shall we expect the release with this feature?

**Comment by deribaucourt** [comment]
@Ehsan2754 The next release will concentrate on container support for running bitbake and various additional language features for bitbake and embedded languages. It should happen in the comming weeks.

devtool support should be part of the following release cycle with no ETA for devtool ide-sdk as of today. We are aiming for Q1 2024.

**Comment by Ehsan2754** [comment]
Using the new feat for devtool.absolutely killing it.   amazing. the ultimate feature would be the image and machine detection and build.

**Comment by deribaucourt** [comment]
Thanks for your feedback, I'm glad you like the new devtool feature! @Ehsan2754

Could you elaborate on "image/machine" detection?

Currently, the machine is not configurable through the interface, it has to be selected through the traditional Yocto environment file local.conf (or external commandWrapper). Meanwhile, the image has to be built like any other standard recipe: either from `.vscode/tasks.json` or the contextual menu.

My idea for integrating machine/distro selection would rely on the incoming Yocto multi-configs and add two selectable fields status bar (similarly to the CMake extension).

**Comment by jrmejiaa** [comment]
Hi!

Thank you for the amazing work. I have been following the extension from the beginning, the changes has been awesome. I want to give my feedback in this case. 

I was not expecting a whole list of all recipes. I don't think it would be useful (over 2k recipes in our setup...) . I do miss a recipe search. I think it would be better for the UX to have this empty and a search to be able to add to the menu and a clean button to erase all (Depending on what I am working on, I could need other set of recipes). 

Thanks for the amazing work.!

**Comment by deribaucourt** [comment]
Thanks a lot for your feedback @jrmejiaa 
I read the whole discussion again. Varying, even opposing propositions have been made around the recipe view enhancements. Here's what I suggest:
 1. Search in the recipes view. We already have it! simply focus on the tab and press Ctrl+F
 2. Adding the list of available recipes when adding a new recipe to the view, with a search functionality. That's what the VSCode "quickPick" will allow.
 3. Do the same for the devtool panel
 4. Add a button to clear the pannel all at once (next to rescan project button on the title line)

**Comment by jrmejiaa** [comment]
Hi @deribaucourt, Thanks for that fast response. 

What I mean with a search in the recipes tab is that it would be really useful to have a search for all recipes there. In that case we would have an easy way to add the recipes that we need in that part. Or when I go to "Bitbake: Add recipe to active workspace" that I write for ex: "dns", the tool would show me the recipes that would match with that pattern.  

For the rest, it looks really good, thanks.

**Comment by deribaucourt** [comment]
@jrmejiaa Have a look at the PR I wrote. You can even try the .vsix generated by the CI:
https://github.com/yoctoproject/vscode-bitbake/pull/114
https://github.com/yoctoproject/vscode-bitbake/actions/runs/7914332171/artifacts/1247555948

It allows searching from all recipes when the "add recipe" button is clicked in the recipes view.
What do you think of it?

![image](https://github.com/yoctoproject/vscode-bitbake/assets/19970889/152d59e2-09d6-4331-9ce8-c4b125c11112)
![image](https://github.com/yoctoproject/vscode-bitbake/assets/19970889/40bbf09f-215d-4ab8-b9e0-7109a273b3b6)


Alternatively, I could change the "plus" icon into a magnifying glass?
I can't change how the search feature works inside the tab. That's handled by VSCode itself. It will search among the recently active recipes.

**Comment by jrmejiaa** [comment]
Hi @deribaucourt thanks for the awesome and fast new tool. It works really good. I have a small comment, it is possible to get the relative path to the workspace from bb/bbappend location? 

It is a very small thing, this new feature is really good! Thanks for the hard work


![Screenshot from 2024-02-15 15-11-22](https://github.com/yoctoproject/vscode-bitbake/assets/23042660/618acf11-68aa-4807-9d53-716cfe93e9e2)

**Comment by deribaucourt** [comment]
I added a commit to show relative paths in the recipes explorer on https://github.com/yoctoproject/vscode-bitbake/pull/114
If you like our extension, you can leave us a positive review on the marketplace :wink: 
Glad to be of help!
