### ISSUE TITLE
Project icon has no background and display poor in the marketplace and with light theme

### ISSUE THREAD

**Issue by microhobby** [yoctoproject/vscode-bitbake#11]
![image](https://github.com/yoctoproject/vscode-bitbake/assets/2633321/8417e440-971d-4b5a-aa84-388f53b15485)

![image](https://github.com/yoctoproject/vscode-bitbake/assets/2633321/0531fa6f-9597-4590-a73c-c0cf2e9f258e)

**Comment by deribaucourt** [comment]
The logo has been updated on the marketplace as part of v2.0.1
