### ISSUE TITLE
"bitbake.parseOnSave": false` has no effect 

### ISSUE THREAD

**Issue by fs570714** [yoctoproject/vscode-bitbake#118]
I think  `"bitbake.parseOnSave": false` has no effect on my side,

I use the extension on a remote system to build yocto images. Every time I press ctrl+s to save a file the bitbake: sanity test runs. I tried to disable it via "bitbake.parseOnSave" in the settings.json and with the checkboxes in Settings however the sanity test still runs.

**Comment by deribaucourt** [comment]
Hello, thanks for your bug report!
This has already been fixed and will be deployed in the next release which is due in the coming weeks
https://github.com/yoctoproject/vscode-bitbake/issues/107

You can download a snapshot from our CI with the fix : https://github.com/yoctoproject/vscode-bitbake/actions?query=is%3Asuccess+branch%3Astaging+event%3Apush
