### ISSUE TITLE
Allow extension to be used for language support without needing to locate/run BitBake

### ISSUE THREAD

**Issue by barndoor2276** [yoctoproject/vscode-bitbake#125]
Currently the extension expects to be able to locate and run BitBake for advanced features. For environments not configured to run BitBake this can be annoying to constantly have VS Code error messages displaying that BitBake could not be located.

For my use case, I develop a BSP in a Windows environment with no support for BitBake and then defer the compilation of my recipes to a remote build server. It would be nice to develop locally with the rich language features of the extension.

**Comment by deribaucourt** [comment]
Hello,
You can disable the advanced features running bitbake in the following ways:
1. Click "Never show again" on the startup message reporting that bitbake is missing
2. Disable "parseOnSave" to additionally stop inspecting bitbake

We provide limited support for Windows, however we do provide full support for build servers through VSCode remote sessions. For instance, if your build server has SSH access, you can start a remote VSCode session on it, install the extension there and run all the bitbake commands. Have a look at this guide for setting it up: https://code.visualstudio.com/docs/remote/remote-overview

**Comment by barndoor2276** [comment]
Thanks for the response. The extension (or maybe VS Code) was not respecting the "Never show again" option yesterday but seems fine after booting up this morning, so perhaps that's good enough. Also I updated to the new extension which may have addressed some of the quirks I was seeing. I could remember to disable parse on save for the bitbake files in my repo if I encounter issues in the future.

I am familiar with the remote sessions extension, unfortunately it won't work in my situation. I think I may be in a unique situation where I develop in a Windows environment, commit, then spin up expensive ephemeral build agents that get destroyed immediately afterwards.

I'm going to close this. Thanks for the suggestions.
