### ISSUE TITLE
Paths from kas-container don't resolve well

### ISSUE THREAD

**Issue by Jesseeee** [yoctoproject/vscode-bitbake#138]
We do all our builds with kas-container, the commandWrapper and so on work perfectly to get the initial setup but one issue we run into is that there are still paths that get picked up as being /work/... for our layers or /build/...
It doesn't seem to be covered by the support that already exists for dockers, or at least not that I'm aware of.
Is this something I can fix with the current options available or is this under the scope of an improvement?

I'm working through WSL/Remotes if that matters

**Comment by deribaucourt** [comment]
Hi! Thanks for your feedback with kas.

We actually have a lot of logic to convert /work and /build paths from the container to the host paths. (It's the function [resolveContainerPath](https://github.com/yoctoproject/vscode-bitbake/blob/162b6b7fecb01a397071440ea80ff6008b1f43ee/client/src/driver/BitBakeProjectScanner.ts#L281)). It should automatically convert the following URLs:
1. Links in the terminal
2. Recipe scan definitions of bitbake variables
3. File URLs in recipe view and general recipe browsing
4. Devtool workspaces update recipe and open workspace commands

They are also tested in CI in unit tests and integration tests.
I haven't tested the WSL+kas combo, maybe there is a specific error there.

Did you encounter a failure to resolve any of the listed items above? Did the broken link appear somewhere else?
Could you provide the extension's logs in the Output window?

**Comment by Jesseeee** [comment]
Hello @deribaucourt thank you very much for the swift response!

Let me first try to explain my kas setup because it's not necessarily traditional (or I'm not sure what is considered "traditional")
We first create a main folder for a build we make let's call it $PRODUCT_BUILD_DIR
in $PRODUCT_BUILD_DIR we checkout layers/meta-$PRODUCT_LAYER with our product specific meta repo
In $PRODUCT_BUILD_DIR we then do a kas checkout on the kas yml contained in layers/meta-$PRODUCT_LAYER/product.yml
This fills up the additional repos under $PRODUCT_BUILD_DIR/layers
And then from $PRODUCT_BUILD_DIR we can just call "kas build layers/meta-$PRODUCT_LATER/product.yml" which is also what we pass to the commandwrapper and we set the working directory correctly in the settings (essentially 2 dirs up from the main product meta layer)

1. terminal links seem to work at first sight, for example during parsing we can get the following path that resolves correctly when i ctrl+click on it
 
```
/build/../work/layers/meta-openembedded/meta-oe/dynamic-layers/networking-layer/recipes-core/packagegroups/packagegroup-meta-oe.bbappend
```

2. To an extent, but I will clarify with my explanation of file URLs

3. To an extent it works, but it's hard to put my finger on what exactly is going wrong, sometimes adding a recipe will only show me "recipe not found" when I click on it, other times I will have a .bb file that is corrrectly resolved, even if it's not in my "main" product layer, but then the $PN_%.bbappend file will show the path as being "/work/layers/...." and be unable to resolve it, 

Bringing me back to 2., so yes the scan definitions work and browsing work as long as it's in a file that it has been able to correctly resolve the path for, if that is not the case I won't see the definitions of those items that originate in unresolveable paths

4. Open workspace, yes as long as the initial recipe can be found, I'm seeing some weird things with for example package exporting recipes, or add-ons to it such as gstreamer, it doesn't seem to be able to resolve any recipe that falls under gstreamer1, update recipe does seem to work from the limited testing I can do, again as long as it can find the original recipe

One weird thing I also just can't explain is why some files resolve and others don't, e.g. a bbappend in one layer from a repo might resolve while another bbappend which is just located in another layer of the exact same repo does not

The only hunch I have is a relation with the type of bb file, I've tried looking at many different recipes and so far all I can find is that if it's a .bb/.inc file it will get resolved, however if it's a .bbappend file it is not

I hope that was all clear, if there's any other info you might require let me know!

Thanks!

**Comment by deribaucourt** [comment]
There may be several errors from what you are describing. It looks like most of the feature is working on your WSL setup since lots of paths are resolved properly. I tried running a kas configuration in a bigger workspace, 20 layers at different levels. It didn't seem to produce issues in itself.

I found a minor bug for recipes that contain a `.` in their name. The recipe was truncated in the recipe view, resulting in "no recipes found". Example: "gstreamer1.0-plugin-imx".

I could also reproduce .bbappend not being resolved (appear as /work/). There was indeed a bug, we handle .bbappends differently and it was missing container paths resolutions.

Here's a PR #140  that fixes what I could reproduce from your issue. Could you download the [.vsix artifact from our CI](https://github.com/yoctoproject/vscode-bitbake/actions/runs/8083702976/artifacts/1283028060), and test it against your setup? Let me know what's fixed/not fixed. Thanks.

I don't really understand why kas-container chose to map the volumes with different paths. It's quite a pain for the IDE :sweat_smile:

**Comment by Jesseeee** [comment]
> There may be several errors from what you are describing. It looks like most of the feature is working on your WSL setup since lots of paths are resolved properly. I tried running a kas configuration in a bigger workspace, 20 layers at different levels. It didn't seem to produce issues in itself.
> 
> I found a minor bug for recipes that contain a `.` in their name. The recipe was truncated in the recipe view, resulting in "no recipes found". Example: "gstreamer1.0-plugin-imx".
> 
> I could also reproduce .bbappend not being resolved (appear as /work/). There was indeed a bug, we handle .bbappends differently and it was missing container paths resolutions.
> 
> Here's a PR #140 that fixes what I could reproduce from your issue. Could you download the [.vsix artifact from our CI](https://github.com/yoctoproject/vscode-bitbake/actions/runs/8083702976/artifacts/1283028060), and test it against your setup? Let me know what's fixed/not fixed. Thanks.
> 
> I don't really understand why kas-container chose to map the volumes with different paths. It's quite a pain for the IDE 😅

Hey @deribaucourt thank you very much for the fix, the . issue was indeed what I was running into! The fix for the container path also resolves my other issues, I think with this everything I've seen so far seems to be fixed and it's for now all working as expected, great job!

Big thanks for these fixes, greatly increases it's utility for me
