### ISSUE TITLE
persist active build folder

### ISSUE THREAD

**Issue by afreof** [yoctoproject/vscode-bitbake#143]
The new buildConfigurations settings array is great. Thank you!

But would it make sense to persist the active build configuration? When selecting a different build configuration, the setting "bitbake.pathToBuildFolder" could be updated.

**Comment by deribaucourt** [comment]
Hi!

It's currently the user's responsibility to edit "pathToBuildFolder" inside their buildConfiguration if they need to. For instance: `settings.json`
```json
{
    "bitbake.pathToEnvScript": "./poky/oe-init-build-env",
    "bitbake.buildConfigurations": [
        {
            "name": "targetA",
            "pathToBuildFolder": "./build-targetA"
        },
        {
            "name": "targetB",
            "pathToBuildFolder": "./build-targetB"
        }
    ]
}
```

Some users could use the same build folder for different configurations even though it's not recommended. It automatically shares the sstate cache and different machines can be built in the same build dir in practice (passing MACHINE through env vars).

Should we enforce that this is not possible? I'm not sure. We could force pathToBuildFolder to be something like build-<buildConfiguration.name>. But some users may require to build somewhere specific, or with a specific name. I prefer flexibility and consistency across settings. What do you think?

**Comment by deribaucourt** [comment]
As discussed on IRC, it looks like you are encountering improper buildCOnifugration settings when restarting VSCode.
We use a "Memento" to keep track of the previous build configuration that was used between VSCode session. You told me the pathToBuildFolder setting used on restart however did not match the selected build configuration. I'll see if I can reproduce this.

**Comment by afreof** [comment]
Yes, that also fine. Closing the issue. Thank you for the explanation.
