### ISSUE TITLE
Setting commandWrapper in buildConfigurations not overwriting global commandWrapper

### ISSUE THREAD

**Issue by kyoungmeyer** [yoctoproject/vscode-bitbake#144]
We use `kas shell <config1>:<config2>:<etc...> -c` as a command wrapper for bitbake, and I'm trying to get this working for multiple build targets in VSCode. I have tried setting a few different versions of config combinations as entries in the `buildConfiguration` array, but they are never used by the bitbake commands. It doesn't seem to matter which name I select from the status bar, the global `bitbake.commandWrapper` (or nothing if the global is not defined) is used. It also seems that other variables aren't re-defined, but I cannot confirm since I don't need to change them.

Here is my settings.json (pared down and sanitized)
```json
{
    "bitbake.buildConfigurations": [
        {
            "name": "Board1",
            "bitbake.commandWrapper": "kas shell <config_base>.yml:<config_1>.yml -c"
        },
        {
            "name": "Board2",
            "bitbake.commandWrapper": "kas shell <config_base>.yml:<config_2>.yml -c",
        }
    ],
    "bitbake.commandWrapper": "kas shell -c",
    "bitbake.workingDirectory": "${workspaceFolder}",
    "bitbake.pathToBuildFolder": "${workspaceFolder}/build",
    "bitbake.pathToBitbakeFolder": "${workspaceFolder}/build/layers/poky/bitbake",
}
```
As of now, the `kas shell -c` is always used as the command wrapper, regardless of the board picked. 

This is on Linux, VSCode 1.87.0, Yocto Project Bitbake Extension v2.2.0

**Comment by deribaucourt** [comment]
Thanks for your detailed explanation,
You don't have to specify the "bitbake." prefix again inside buildConfigurations:
```json
    "bitbake.buildConfigurations": [
        {
            "name": "Board1",
            "commandWrapper": "kas shell <config_base>.yml:<config_1>.yml -c"
        },
        {
            "name": "Board2",
            "commandWrapper": "kas shell <config_base>.yml:<config_2>.yml -c",
        }
    ],
```
Should work. Unfortunately VSCode knows the allowed property names for settings objects but doesn't report errors on them.

**Comment by kyoungmeyer** [comment]
That did indeed fix it. Thanks so much. Now that I know what to look for, I can see that the documentation shows the correct formatting, and I just read it wrong. I'll mark this closed.
