### ISSUE TITLE
Embedded languages diagnostics generate problems for background virtual files

### ISSUE THREAD

**Issue by Thuna7** [yoctoproject/vscode-bitbake#169]
Despite configuring the Yocto BitBake extension, I'm encountering compatibility issues when used alongside the ShellCheck extension in VSCode. Specifically, I receive errors from the following file only when the Yocto BitBake extension is enabled:

~/.vscode-server/data/User/workspaceStorage/073f7e157f535776aa165b2f075bf852/yocto-project.yocto-bitbake/embedded-documents/c42156fb-8176-41de-9edb-4263f51e74fe.py

In an attempt to resolve this, I excluded the .vscode-server directory in my settings.json file using the following configuration:

"shellcheck.ignorePatterns": {
    "\*\*/.vscode-server/\*\*": true
}

However, the problem persists with the file. Any suggestions on how to address this?

**Comment by idillon-sfl** [comment]
If you mean errors and warnings in the "PROBLEMS" tab, then it is normal and expected, unfortunately.
![Screenshot from 2024-03-11 11-18-28](https://github.com/yoctoproject/vscode-bitbake/assets/92585455/11940904-6ff8-4554-b29a-8965f4987031)

If you mean anything else, then it is a problem we are still not aware of. In that case, please provide us with more information, such as the error message or a screenshot. Thank you

**Comment by Thuna7** [comment]
> If you mean errors and warnings in the "PROBLEMS" tab, then it is normal and expected, unfortunately. 

That's exactly the issue I meant. Thank you for your support; I'll close the issue.
