### ISSUE TITLE
Error when saving files with neovim

### ISSUE THREAD

**Issue by antznin** [yoctoproject/vscode-bitbake#214]
Hi,

First of all, thank you for this project.

I'm wondering about a design choice here, which may be completely intended - just bare in mind that I am not experienced with language servers and vscode.

I was interested in using this project but vscode not being my primary editor, I gave a shot at setting up the server-side only in my neovim environment. I got as far as having auto-completion work, with help snippets from the documentation (excellent!).

I got this error as soon as I saved my file:

```
[WARN][2024-05-04 23:10:28] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"bitbake/parseAllRecipes"
[ERROR][2024-05-04 23:10:28] .../vim/lsp/rpc.lua:734	"rpc"	"language-server-bitbake"	"stderr"	"…/node_modules/vscode-jsonrpc/lib/common/connection.js:565
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: MethodNotFound
    at handleResponse (…/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)
    at handleMessage (…/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)
    at processMessageQueue (…/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (…/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at process.processImmediate (node:internal/timers:478:21) {
  code: -32601,
  data: undefined
}

Node.js v22.1.0"
```

After digging a little, it turns out this call it what makes saving fail at the moment: https://github.com/yoctoproject/vscode-bitbake/blob/40319e66bf466fbc60536cfeee5f807bb0a5b578/server/src/server.ts#L201

I can see that the logic for parsing recipes is done on the client side - so unsurprisingly that won't work with my current client.

My thoughts/questions:

- Are there constraints that make having the logic in the client (vscode specific stuff)?
- Having this logic done on the server would make this project portable on many code editors.
- If this were to be possible but time-demanding, could we consider restricting the features of the server for editors other than vscode in the meantime?

Thanks,
Antonin

**Comment by deribaucourt** [comment]
Hello! Thanks for reporting this issue. We've moved the "on save" handler to the client side now for this kind of reasons. You should not encounter this error if you test our staging branch. Otherwise, wait for the next release :).

Testing this also made me develop my debugging skills for CoC.nvim! I was able to find a regression and fixed it in #220 

Note to self: to get debug output, follow instructions at https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by deribaucourt** [comment]
I haven't encountered other errors in the logs. Let me know if you find any

**Comment by antznin** [comment]
Hi @deribaucourt, I finally got around to test this, and it works now (2.5.0)! Thanks
