### ISSUE TITLE
Embedded python language pylint/flake8 not respecting project settings, general issues

### ISSUE THREAD

**Issue by staehle** [yoctoproject/vscode-bitbake#233]
Hi, I just updated my bitbake plugin to 2.5.0 from 2.0.1, and started noticing some issues with the new embedded language stuff.

1. I can't seem to disable pylint and flake8 parsing, and it doesn't seem to be respecting any project setting relating to those.
2. I'm getting pylint/flake8 warnings/errors outside of python functions.

This is how I have my project settings setup, and the BitBake parsing part works just fine:

```json
{
"settings": {
		"editor.formatOnSave": false,
		"files.watcherExclude": {
			"**/__pycache__": true,
			"**/.git/objects/**": true,
			"**/.git/subtree-cache/**": true,
			"**/build/**": true,
			"**/build-*/**": true,
		},
		"flake8.args": [
			"--ignore=E203,E501,W504,E401,E402,F401"
		],
		"pylint.args": [
			"--init-hook=\"import os,sys; from pathlib import Path; lp=list(Path(os.getcwd()).parts); base=Path('/' + '/'.join(lp[1:lp.index('bitbake')+1]) + '/lib'); sys.path.insert(0, str(base));\"",
			"-d E0401,W0611,C0413,C0410,C0411,C0116,C0103,W0602,C0301,E1205,C0209,C0114,E0611"
		],
		"python.analysis.exclude": [
			"**/__pycache__",
			"**/.git/objects/**",
			"**/.git/subtree-cache/**",
			"**/build/**",
			"**/build-*/**",
		],
		"python.autoComplete.extraPaths": [
			"/media/x/super-firmware/sources/utilities/bitbake/lib",
			"/media/x/super-firmware/sources/oe/openembedded-core/meta/lib",
		],
		"python.analysis.extraPaths": [
			"/media/x/super-firmware/sources/utilities/bitbake/lib",
			"/media/x/super-firmware/sources/oe/openembedded-core/meta/lib",
		],
		"python.analysis.include": [
			"/media/x/super-firmware/sources/utilities/bitbake",
			"/media/x/super-firmware/sources/oe/openembedded-core/meta/lib",
		],
		"bitbake.pathToBitbakeFolder": "/media/x/super-firmware/sources/utilities/bitbake",
		"bitbake.pathToBuildFolder": "/media/x/super-firmware/build-vscode",
		"bitbake.pathToEnvScript": "/media/x/super-firmware/sources/oe/openembedded-core/oe-init-build-env",
		"bitbake.shellEnv": {
			"BITBAKEDIR": "/media/x/super-firmware/sources/utilities/bitbake"
		}
	}
}
```

e.g. Here's a couple examples of what I see when opening `meta/classes-global/buildstats.bbclass` : 

![image](https://github.com/yoctoproject/vscode-bitbake/assets/6710147/0f72967c-cfca-474d-8597-2c05f7a66e37)

Here, I'm getting random problems outside of bitbake python functions.

![image](https://github.com/yoctoproject/vscode-bitbake/assets/6710147/902a4596-a993-4c42-bcc8-8db33000b72b)

I very much have pylint `C0410` and flake8 `E401` disabled in my project settings above, and yet they're showing up here. When I look at the vscode output console for this file, I see this:

`2024-06-01 15:47:56.051 [info] /usr/bin/python3 -m flake8 --format='%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s' /home/jstaehle/.vscode-server/data/User/workspaceStorage/dd7d453cda182a04308177c4bda0c273-1/yocto-project.yocto-bitbake/embedded-documents/65eebb7257dab5cae1d1c48c1b23d9a7.py`

None of the options are getting passed in.  Compare that to when I open `bitbake/lib/bb/utils.py`: 

`2024-06-01 15:47:59.221 [info] /usr/bin/python3 -m flake8 --format='%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s' --ignore=E203,E501,W504,E401,E402,F401 /media/x/super-firmware/sources/utilities/bitbake/lib/bb/utils.py`

Not sure what to tell you about the other issue, but maybe having an option to turn off just flake8/pylint for the embedded python stuff without turning off the whole thing would be nice?

Thanks!

**Comment by idillon-sfl** [comment]
This happens because we create Python files in the background and forward the diagnostics generated from these Python files to the BitBake files. These generated files have additional white spaces and imports.

Supporting linters properly and ensuring they don't show undesired diagnostics might be possible, but it would require a considerable amount of effort. For now, I plan to simply ignore all diagnostics generated by anything other than ms-python.python.

I am surprised this problem was not reported before version 2.5, though. Also, I am not sure why the settings are not respected.
