### ISSUE TITLE
devtool modify workspaces are not consistent

### ISSUE THREAD

**Issue by afreof** [yoctoproject/vscode-bitbake#309]
If `devtool modify` is called from the command line, VSCode does not list the recipe in the “DEVTOOL WORKSPACE” section. The situation is even worse if the workspace is set up via the user interface but deleted via `devtool reset`: There is no way to remove the recipe from the “DEVTOOL WORKSPACE” section.

Probably the solution should be that VSCode takes the status from the workspace folder by checking if some folders and files exist instead of saving the status in its internal configuration files.

**Comment by deribaucourt** [comment]
So we do not display the devtool workspaces out of an "internal configuration file". We parse the `devtool status` output.

**Comment by deribaucourt** [comment]
You can trigger the "Rescan" command through the command pallette (Ctrl+Shift+P), or by clicking the button shaped in a circling arrow on the Yocto Panel, or click the Yocto status bar.

**Comment by afreof** [comment]
Hi Enguerrand

Thank you for your response. That is at least much better than what I was assuming. And I also see that challenge for making it even better without taking some assumptions which might be wrong.

I'm going to close this issue.
