### ISSUE TITLE
Show in recipes explorer skipped recipes

### ISSUE THREAD

**Issue by Paullgk** [yoctoproject/vscode-bitbake#317]
Currently, when scanning the project the extension prevents to add in recipes explorer the recipe that have been skipped by Bitbake. 
As an example, if I want to add the the package `virt-manager` from `meta-virtualization` (https://git.yoctoproject.org/meta-virtualization/tree/recipes-extended/virt-manager/virt-manager_4.1.0.bb?h=master); it requires by default `wayland` or `x11`  distro features, and so will be skipped if the latter are not in the image being built:

```bash
pleguendekerneizon@ffde7735d379:~/PROJECTS/SEAPATH/seapath_yocto/build$ bitbake-layers show-recipes | grep virt-mana -C 5
  meta                 9.1.0114
vim-tiny:
  meta                 9.1.0114
virglrenderer:
  meta                 1.0.1 (skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES))
virt-manager:
  meta-virtualization  4.1.0 (skipped: one of 'x11 wayland' needs to be in DISTRO_FEATURES)
virt-viewer:
  meta-virtualization  11.0 (skipped: one of 'wayland x11' needs to be in DISTRO_FEATURES)
virt-what:
  meta-virtualization  1.21
```

The behavior of the extension is to not show at all the skipped recipe:
![image](https://github.com/user-attachments/assets/f420f4cc-be31-47d7-8cbb-2ace5f29171d)

A nice feature would be to show the skipped recipe and display them maybe with a warning. The fact that recipe is not showing at all may lead to think a bug although this is an expected behavior.

**Comment by deribaucourt** [comment]
Currently, we discard them from the recipe view. This would indeed allow users to keep browsing their files and determine why it was skipped. The implementation should be simple enough:

- Add a "skipped" attribute in our recipe scan data structure
- No longer discard skipped recipes, add the skipped attribute
- Show the skipped attribute in the recipes view

**Comment by deribaucourt** [comment]
Here's a preview that's going to be part of the next release
![image](https://github.com/user-attachments/assets/684d0bc0-38e5-49f9-8e42-0351ba5f50d1)
