### ISSUE TITLE
Support for VS Code web

### ISSUE THREAD

**Issue by microhobby** [yoctoproject/vscode-bitbake#39]
Should be possible to have at least a syntax highlight support for VS Code web:

![image](https://github.com/yoctoproject/vscode-bitbake/assets/2633321/0d9c2abc-1312-435c-90b8-2bad060c8d62)

**Comment by deribaucourt** [comment]
Migration to web extension is [documented here](https://code.visualstudio.com/api/extension-guides/web-extensions#update-existing-extensions-to-web-extensions).
Most of our contribution points would not work without the NodeJS code but highlighting would be nice to have indeed.

**Comment by deribaucourt** [comment]
Contributions welcome to provide any kind of limited support for the Web editor
