### ISSUE TITLE
Split this project into two projects: server and client

### ISSUE THREAD

**Issue by Freed-Wu** [yoctoproject/vscode-bitbake#40]
Comes from <https://github.com/yoctoproject/vscode-bitbake/issues/22>. Split this project into server and client can allow other editors use the server, and [coc.nvim](https://github.com/neoclide/coc.nvim) use the client. As a reference, there are some projects do in this method:

- [marksman](https://github.com/artempyanykh/marksman): A language server for markdown.
  - [marksman-vscode](https://github.com/artempyanykh/marksman-vscode): The VS Code extension of `marksman`
  - [coc-marksman](https://github.com/yaegassy/coc-marksman): The Coc extension of `marksman`
- [texlab](https://github.com/latex-lsp/texlab): A language server for LaTeX
  - [texlab-vscode](https://github.com/latex-lsp/texlab-vscode): The VS Code extension of `texlab`
  - [coc-texlab](https://github.com/fannheyward/coc-texlab): The Coc extension of `texlab`
- [clangd](https://github.com/clangd/clangd): A language server for C/C++
  - [vscode-clangd](https://github.com/clangd/vscode-clangd): The VS Code extension of `clangd`
  - [coc-clangd](https://github.com/clangd/coc-clangd): The Coc extension of `clangd`

I think it can be useful for the other users who don't use VS Code.

**Comment by deribaucourt** [comment]
Hello @Freed-Wu,
[This message](https://github.com/yoctoproject/vscode-bitbake/issues/22#issuecomment-1840726844) explains why splitting the server/client packages is not the only step necessary to be compatible with other editors. Support for other editors is not planned at this stage.

**Comment by Freed-Wu** [comment]
You misunderstand my meaning. The message comes from my trial and I just try to explain that separate this project to server can make other editor use the server and separate this project to client can make coc.nvim use the extension.

**Comment by deribaucourt** [comment]
So you would also be running the client with VIM? That's interesting! You'd probably have to map all our calls to the vscode API which is quite a lot. If you ever make it work with VIM, please share it through a PR!

**Comment by Freed-Wu** [comment]
> map all our calls to the vscode API

I think [coc.nvim](https://github.com/neoclide/coc.nvim) have done this work. This is an example: <https://samroeca.com/coc-plugin.html>

**Comment by Freed-Wu** [comment]
I have taken a look and I think this project can be splitted to three projects:

## vscode-bitbake-lib

A library used by language server and language client

## language-server-bitbake

A program can be used by all editors who support LSP. Just

```sh
npm install -g language-server-bitbake
language-server-bitbake --stdio
```

to run it.

## `yocto-bitbake`

should name it `vscode-bitbake` more exactly. It can be ported to coc.nvim.

I have take experiments to port some VS code extension to coc.nvim and they can work for me:

- [coc-mlir](https://github.com/Freed-Wu/coc-mlir): ported from [vscode-mlir](https://github.com/llvm/vscode-mlir), language client fro mlir.
- [coc-nix](https://github.com/Freed-Wu/coc-nix): ported from [vscode-nix-ide](https://github.com/nix-community/vscode-nix-ide): language client for nix lang.

I have two ideas:

1. Host these 3 projects in one repo like https://github.com/microsoft/vscode-languageserver-node, However publish these 3 library to npm to make it available.
2. Split them to 3 repos, Add the lib and language server to the dependence of language client to replace `installServerIntoExtension`.
