### ISSUE TITLE
Running plugin under windows

### ISSUE THREAD

**Issue by hvdbrand** [yoctoproject/vscode-bitbake#42]
I am running Windows on my development machine and run bitbake inside a docker container.
I run VSCode under Windows and want to have the highlighting, but do not have bitbake running.
Is it possible to disable the checks for the bitbake executable?
(That could also help people browsing a layer without building it locally).

Another alternative I could consider is configuring a devcontainer.
Has the plugin been tested in combination with a devcontainer?

**Comment by deribaucourt** [comment]
Hi, thanks for your feedback!
You can disable the error notification by clicking the "Close" button that appears with it. (I tshould be the "Don't show again button" but there's a bug in this release that's fixed for the next one).

The next release will support running bitbake through "docker run" and other tools, but I'm curious to know if that'll work on Windows. You may preview this feature by installing the ".vsix" from the staging branch produced by [our CI](https://github.com/yoctoproject/vscode-bitbake/actions?query=branch%3Astaging+event%3Apush+is%3Asuccess).

With the current release, you may also run VSCode inside your docker container by enabling SSH access to it and using an SSH remote VSCode session ([documented here](https://code.visualstudio.com/docs/remote/ssh)). This should enable the bitbake features.

Let me know how that turns out!

**Comment by microhobby** [comment]
> Another alternative I could consider is configuring a devcontainer. Has the plugin been tested in combination with a devcontainer?

yes, works like in a bare Linux

**Comment by deribaucourt** [comment]
Thanks a lot for testing this @microhobby!
There should be some error logs in the output view for Bitbake or Bitbake language server.
Windows support is not a priority in our current roadmap. I advise Windows users to use remote SSH or container VSCode sessions on a compatible Linux environment for the time being.

**Comment by microhobby** [comment]
> Thanks a lot for testing this @microhobby! There should be some error logs in the output view for Bitbake or Bitbake language server. Windows support is not a priority in our current roadmap. I advise Windows users to use remote SSH or container VSCode sessions on a compatible Linux environment for the time being.

Bitbake Language Server:

```
[onInitialize] Initializing connection
[Error - 9:17:46 AM] Server initialization failed.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:46 AM] Bitbake Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Info  - 9:17:49 AM] Connection to server got closed. Server will restart.
true
[onInitialize] Initializing connection
[Error - 9:17:49 AM] Server initialization failed.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:49 AM] Bitbake Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:49 AM] Restarting server failed
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Info  - 9:17:51 AM] Connection to server got closed. Server will restart.
true
[onInitialize] Initializing connection
[Error - 9:17:51 AM] Server initialization failed.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:51 AM] Bitbake Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:51 AM] Restarting server failed
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Info  - 9:17:53 AM] Connection to server got closed. Server will restart.
true
[onInitialize] Initializing connection
[Error - 9:17:54 AM] Server initialization failed.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:54 AM] Bitbake Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:54 AM] Restarting server failed
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Info  - 9:17:56 AM] Connection to server got closed. Server will restart.
true
[onInitialize] Initializing connection
[Error - 9:17:56 AM] Server initialization failed.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:56 AM] Bitbake Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:56 AM] Restarting server failed
  Message: Request initialize failed with message: Invalid URL
  Code: -32603 
[Error - 9:17:58 AM] The Bitbake Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

Bitbake output is empty;

Whould be good to have a platform check and never try to roll up the server if in windows then.

**Comment by deribaucourt** [comment]
Yes I can specify that the extension is only available for Linux platforms in the next release. This has to be done through the `vsce` arguments passed during `npm run package`.

**Comment by hvdbrand** [comment]
Your last post seems to  suggest that the puffin will only be available on Linux. I would still like to be able to run it in Windows.

To my understanding,  @microhobby suggests to not try to start the server when running in Windows. I guess a runtime check is better and would cover my preferred usecase: running in a devcontainer in Windows.

**Comment by deribaucourt** [comment]
Right now it seems that the extension does nothing but crash on native Windows which is why I'm thinking about disabling Windows support in the 2.1 release. You should still be able to install it inside containers and SSH remote VSCode sessions that use a Linux container.
Due to user feedback, we may investigate Windows compatibility for the next release though :spiral_notepad:

**Comment by Axtmann** [comment]
Hi. I'm not sure if this fits here, but I can not install 2.1 version using "Remote - SSH" or "Remote - WSL" addons while running VSCode on Windows and WSL/SSH target on "Ubuntu 22.04". Version 2.0.1 works as expected. Update to 2.1.0 is not suggested by VSCode, reinstalling will install 2.0.1 instead. Using "Install another version" I can see 2.1.0 but if I try to install it, VSCode will just say "installed" but no change takes place, 2.0.1 is still installed. Same behavior in VSCode and VSCode insider.

**Comment by WilsonZiweiWang** [comment]
> Hi. I'm not sure if this fits here, but I can not install 2.1 version using "Remote - SSH" or "Remote - WSL" addons while running VSCode on Windows and WSL/SSH target on "Ubuntu 22.04". Version 2.0.1 works as expected. Update to 2.1.0 is not suggested by VSCode, reinstalling will install 2.0.1 instead. Using "Install another version" I can see 2.1.0 but if I try to install it, VSCode will just say "installed" but no change takes place, 2.0.1 is still installed. Same behavior in VSCode and VSCode insider.

We package the extension with certain architectures since the change in this commit:
https://github.com/yoctoproject/vscode-bitbake/commit/185c4afbbe746c5d2f62c30aabb21999f7762258

**Comment by Axtmann** [comment]
> We package the extension with certain architectures since the change in this commit: [185c4af](https://github.com/yoctoproject/vscode-bitbake/commit/185c4afbbe746c5d2f62c30aabb21999f7762258) Versions before 2.1 were packaged on all platforms.

Thanks for the feedback. Yes, I saw this change, which is why I asked about it in this, referenced ticket.  With 2.0 my case worked without crash though and deribaucourt above said:
> You should still be able to install it inside containers and SSH remote VSCode sessions that use a Linux container.

Which at least for me, doesn't seem to work.

**Comment by deribaucourt** [comment]
@Axtmann Thanks for your feedback!

We disabled Windows in the current version because of the crash. If I understood correctly, it also made it impossible to install inside a Linux container SSH session? This looks more like a VSCode extension manager bug. I suggest using 2.0.1 for the time being.

We plan to properly address Windows in the next releases and add back that compatibility while fixing the crashes. Even if some features might be disabled for windows.
