### ISSUE TITLE
VS Code variables support in settings

### ISSUE THREAD

**Issue by shplack** [yoctoproject/vscode-bitbake#56]
I think it would be great to add support for VS Code variables in BitBake's settings. This would greatly improve usage of the upcoming `commandWrapper` setting, especially for us who use the docker image `crops/poky` to build.

For example:
`${env:HOME}` should translate to `/home/user`

> Tested on 323260e

P.S.
Thanks for the amazing work! I've been looking forward to an official extension for a while now 🤓

**Comment by deribaucourt** [comment]
Hi and thanks for your positive feedback!
I'm not sure I understand where you would like `${env:HOME}` to be translated: In embedded python? In Bitbake variable assignments? Could you provide an example code and how you expect the translation to be presented to the user (hover tooltip, definition link, ...).

On staging, it's currently possible to inject bitbake variables to the build through the following means:

1. Using the `commandWrapper` setting to point to a script, or pass `-e` env vars to docker. Which also needs `[BB_ENV_PASSTHROUGH_ADDITIONS](https://docs.yoctoproject.org/bitbake/2.0/bitbake-user-manual/bitbake-user-manual-ref-variables.html#term-BB_ENV_PASSTHROUGH_ADDITIONS)`
2. Using the `shellEnv` setting together with [BB_ENV_PASSTHROUGH_ADDITIONS](https://docs.yoctoproject.org/bitbake/2.0/bitbake-user-manual/bitbake-user-manual-ref-variables.html#term-BB_ENV_PASSTHROUGH_ADDITIONS)

These variables will be effective for all the bitbake commands and tasks that pop up in the terminal, as well as bitbake scans which produce a lot of features across bitbake files. However there is no connection yet with these and embedded languages.

**Comment by shplack** [comment]
Sorry if I was unclear, but I meant being able to use [VS Code's own variable replacements](https://code.visualstudio.com/docs/editor/variables-reference).

For example in `settings.json`:
```json 
{
    "bitbake.commandWrapper": "docker run --rm -v ${env:HOME}/.ssh:/home/pokyuser/.ssh crops/poky /bin/bash -c"
}
```

_See [**Environment variables**](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables)_

So far, I see that `${workspaceFolder}` support exists, it would be great if all of VS Code,s variable replacements could be used in settings and/or even in tasks/launches.

Hopefully I've made it clear now 🙂

**Comment by shplack** [comment]
Ah, maybe I was incorrect about it not being supported in tasks/launches, but nonetheless I mean that it would be good to have support for it in settings.

> So we actually handle the parsing of ${workspaceFolder} [internally here](https://github.com/yoctoproject/vscode-bitbake/blob/159bf008253835579f112ec148ad5dd089c12a4b/client/src/lib/src/BitbakeSettings.ts#L46):
> ``` js
> function expandWorkspaceFolder (configuration: string, workspaceFolder: string): string {
>   return sanitizeForShell(configuration.replace(/\${workspaceFolder}/g, workspaceFolder)) as string
> }
> ```

I noticed this, and I was wondering why not _all_ VS Code's variable expansions are not supported. There really isn't an API for this? Sadge 

I wouldn't expect any repo owner to manually include each variable expansion that VS Code supports. But maybe for this use case, it would be reasonable to ask for `${env:XXX}` since expansion need only be done for "1" (`env`) and expanding everything between `:` to `}`?

**Comment by deribaucourt** [comment]
Yes it's definitely not too complicated to do it internally. We can create a separate function that `configuration.replace` over more variables. In that case, env vars are available through `process.env`.
Ideally it should be done by VSCode as many extension developers have requested for years.
I'll add it to my TODO list unless you want to contribute, which would be very welcome :)

**Comment by shplack** [comment]
I would love to contribute if I simply had the time! If it doesn't get prioritized in the future then, if I find the time, I'll put my JavaScript hat on and try to do it myself. Have a good day! :)

**Comment by deribaucourt** [comment]
@shplack I made a PR that adds support for `${env:VAR}` settings substitution. Would you be kind enough to try it out and tell me if that's what you expect?
You can download and install[ the .vsix generated](https://github.com/yoctoproject/vscode-bitbake/actions/runs/7461554289/artifacts/1156747772) by the CI. Make sure to disable auto updates as the version number is backwards in that branch.

**Comment by shplack** [comment]
> @shplack I made a PR that adds support for `${env:VAR}` settings substitution. Would you be kind enough to try it out and tell me if that's what you expect? You can download and install[ the .vsix generated](https://github.com/yoctoproject/vscode-bitbake/actions/runs/7461554289/artifacts/1156747772) by the CI. Make sure to disable auto updates as the version number is backwards in that branch.

Unfortunately, the task "Parse all recipes" now results in an error.
<img src="https://private-user-images.githubusercontent.com/62137686/295469401-f594b0d5-c289-41bf-a5b3-d1ec2dcdb227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Njc5OTYsIm5iZiI6MTcwNDg2NzY5NiwicGF0aCI6Ii82MjEzNzY4Ni8yOTU0Njk0MDEtZjU5NGIwZDUtYzI4OS00MWJmLWE1YjMtZDFlYzJkY2RiMjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA2MjEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZTJmYzIyODdhOWNlYjdhM2Q2NDZiMjMxN2E2ZjRlMTZiMDlkNDExNzRjMDhkMzgzZTk5MjAyNzdhNjRjNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q7rR1YOHNzC2LvFhyL-ncBPz-11L5l94vkh4Iug-VWw"  width="341" height="158">

**Comment by shplack** [comment]
> @shplack I made a PR that adds support for `${env:VAR}` settings substitution. Would you be kind enough to try it out and tell me if that's what you expect? You can download and install[ the .vsix generated](https://github.com/yoctoproject/vscode-bitbake/actions/runs/7461554289/artifacts/1156747772) by the CI. Make sure to disable auto updates as the version number is backwards in that branch.

After testing parsing/scanning, running a task for and building a recipe, this seems to do exactly what I would like it to do!
