### ISSUE TITLE
Suggestion: Publish this in Open-VSX

### ISSUE THREAD

**Issue by patnan** [yoctoproject/vscode-bitbake#71]
We are using CodeOSS, not VSCode, and thus we cannot use this due to legal reasons since it is not allowed to use MS Marketplace for anything else than VSCode.

Could you also publish this in Open-vsx.org?
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by WilsonZiweiWang** [comment]
Hi,
This is of low priority in our current scope and the tests for the publication to a new platform as well as the support for advanced features will require some work.

Will update you in case of any advancements. Thank you.

**Comment by patnan** [comment]
Would you mind if we did the publishing on open-vsx?

**Comment by deribaucourt** [comment]
Hello @patnan 
Have you tested our .vsix on code OSS?
You can download the latest .vsix artifact [from the CI](https://github.com/yoctoproject/vscode-bitbake/actions/workflows/main.yml?query=branch%3Amain)

I identified a few possible limitations that would apply to code-oss:
 1. Remote development extensions for build servers (SSH) seem to not exist (that would be a limitation
 2. We rely on bash-ide and some other intelliSense extensions. I see they are available on code-oss but with lightly outdated versions

I got the following error when trying to install the .vsix:
```
Unable to install extension 'yocto-project.yocto-bitbake' as it is not compatible with VS Code '1.74.3'.
```
It looks like some compatibility issues would need to be addressed before publishing to open-vsx. Feel free to make a PR if you are willing to fix them!

Once we have a working open-vsx port, we could consider publishing. Ideally, we should setup an official yocto-project publisher. We'll ask the Yocto project credential maintainers if they are interested in open-vsx support as well to generate the publisher.

**Comment by deribaucourt** [comment]
Contributions welcome to provide any kind of limited support for Open-VSX
