### ISSUE TITLE
Avoid editing .vscode/settings.json

### ISSUE THREAD

**Issue by afreof** [yoctoproject/vscode-bitbake#95]
If the settings.json file is in git the plugin needs to be disabled for many common workflows.
For example when working with git, the plugin does very nasty things:

- git stash
- The settings.json file gets stashed
- The plugin starts working acc. the sttings.json file which is in git.
In my case this referees for example to a different build folder.
- The plugin generates a new settings.json file
- git stash pop tries to restore the settings.json but vscode is quicker and git stash pop conflict ends in a conflict on the settings.json file.

Writing settings into a file which is in git but written by vscode is not ideal.
There are many related issues on github. For example this tries to
introduce config snippets to VSCode: https://github.com/microsoft/vscode/issues/15909

Removing the settings.json from git leads to other issues as mentioned in the commit message of: https://git.yoctoproject.org/poky/commit/?id=5ff688fe29bd644e28a226b655b3fdcce8a8ebb8

As a minimal, quick workaround we could try to update the settings.json in poky with settings which will not be altered by the plugin. Here is a commit which I could send: https://git.yoctoproject.org/poky-contrib/log/?h=adrianf/vscode-yocto-plugin. Wdyt?

**Comment by deribaucourt** [comment]
config snippet would be the prefered way to go indeed! Some other extensions like vscode-meson have to edit settings like us sadly.

The settings you suggest for poky are the way to go IMO. Especially since they are now versionable thanks to https://github.com/yoctoproject/vscode-bitbake/pull/19

I suggest a few modifications to align with the VSCode default values on some external settings and also to unset user customization on bitbake variables if they existed. In my case, I define a workDir at the user level. It must be disabled for the poky configuration to work.
```
{
    "files.watcherExclude": {
        "**/.git/**": true,
        "**/cache/**": true,
        "**/tmp*/**": true,
        "**/downloads/**": true,
        "**/sstate-cache/**": true,
        "**/vscode-bitbake-build/**": true,
        "**/workspace/sources/**": true,
        "**/workspace/attic/**": true
    },
    "files.exclude": {
        "**/.git/**": true,
        "**/cache/**": true,
        "**/tmp*/**": true,
        "**/downloads/**": true,
        "**/sstate-cache/**": true,
        "**/vscode-bitbake-build/**": true,
        "**/workspace/sources/**": true,
        "**/workspace/attic/**": true
    },
    "python.analysis.exclude": [
        "**/.git/**",
        "**/cache/**",
        "**/tmp*/**",
        "**/downloads/**",
        "**/sstate-cache/**",
        "**/vscode-bitbake-build/**",
        "**/workspace/sources/**",
        "**/workspace/attic/**"
    ],
    "bitbake.pathToBitbakeFolder": "${workspaceFolder}/bitbake",
    "bitbake.pathToEnvScript": "${workspaceFolder}/oe-init-build-env",
    "bitbake.pathToBuildFolder": "${workspaceFolder}/build",
    "bitbake.commandWrapper": "",
    "bitbake.workingDirectory": "",
    "python.autoComplete.extraPaths": [
        "${workspaceFolder}/bitbake/lib",
        "${workspaceFolder}/meta/lib"
    ],
    "python.analysis.extraPaths": [
        "${workspaceFolder}/bitbake/lib",
        "${workspaceFolder}/meta/lib"
    ],
    "[python]": {
        "diffEditor.ignoreTrimWhitespace": false,
        "gitlens.codeLens.symbolScopes": [
            "!Module"
        ],
        "editor.formatOnType": true,
        "editor.wordBasedSuggestions": "off",
        "files.trimTrailingWhitespace": false
    },
    "[shellscript]": {
        "files.eol": "\n",
        "files.trimTrailingWhitespace": false
    }
}
```

**Comment by afreof** [comment]
Sent a patch: https://lists.openembedded.org/g/openembedded-core/message/195246

**Comment by afreof** [comment]
Next try is to generate the setting.json from oe-init-build-env script: https://git.yoctoproject.org/poky-contrib/log/?h=adrianf/vscode-yocto-plugin. Maybe that's the way to go until VSCode support config snippets.

**Comment by afreof** [comment]
Closing this issue. Conclusion is that the settings.json file must not be in git. For poky there is now a settings.json file generated by the oe-init-build-env script. This works well.
